// ProductRequest.java
package com.marketplace.emarketplacebackend.dto;

import lombok.Data;


import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Data
public class ProductRequest {
   
    @NotBlank(message = "Product name cannot be blank")
    @Size(max = 255, message = "Product name cannot exceed 255 characters")
    private String name;

    @NotBlank(message = "Description cannot be blank")
    private String description;

    @NotNull(message = "Price cannot be null")
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    private Double price;

    @NotNull(message = "Stock cannot be null")
    @Min(value = 0, message = "Stock cannot be negative")
    private Integer stock;

    @NotBlank(message = "Category name cannot be blank")
    private String categoryName;

    @NotNull(message = "Store ID cannot be null")
    private Long storeId; 

    // ALL GETTERS AND SETTERS ARE NOW GENERATED BY LOMBOK.
    // You can delete them from here after refreshing your Gradle project 
}